[versions]
hilt = "2.44"

[libraries]
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt"}
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

[plugins]
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[bundles]

